Mock.mock("/myJD", {
    data: {
        item1: [{
            des: "待处理订单",
            href: '@url(http)'
        }, {
            des: "消息",
            href: '@url(http)'
        }, {
            des: "返修退换货",
            href: '@url(http)'
        }, {
            des: "我的问答",
            href: '@url(http)'
        }, {
            des: "降价商品",
            href: '@url(http)'
        }, {
            des: "我的关注",
            href: '@url(http)'
        }],
        item2: [{
            des: "我的京豆",
            href: '@url(http)'
        }, {
            des: "我的优惠卷",
            href: '@url(http)'
        }, {
            des: "我的白条",
            href: '@url(http)'
        }, {
            des: "我的理财",
            href: '@url(http)'
        }]
    }

})
Mock.mock("/location", {
    data: {
        'mainLand': [{
            "id": 0,
            "city": '北京',
            "href": "@url(http)"
        }, {
            "id": 1,
            "city": '上海',
            "href": "@url(http)"
        }, {
            "id": 2,
            "city": '天津',
            "href": "@url(http)"
        }, {
            "id": 3,
            "city": '重庆',
            "href": "@url(http)"
        }, {
            "id": 4,
            "city": '福建',
            "href": "@url(http)"
        }, {
            "id": 5,
            "city": '河北',
            "href": "@url(http)"
        }, {
            "id": 6,
            "city": '山西',
            "href": "@url(http)"
        }, {
            "id": 7,
            "city": '河南',
            "href": "@url(http)"
        }, {
            "id": 8,
            "city": '辽宁',
            "href": "@url(http)"
        }, {
            "id": 9,
            "city": '吉林',
            "href": "@url(http)"
        }, {
            "id": 10,
            "city": '黑龙江',
            "href": "@url(http)"
        }, {
            "id": 11,
            "city": '内蒙古',
            "href": "@url(http)"
        }, {
            "id": 12,
            "city": '江苏',
            "href": "@url(http)"
        }, {
            "id": 13,
            "city": '山东',
            "href": "@url(http)"
        }, {
            "id": 14,
            "city": '安徽',
            "href": "@url(http)"
        }, {
            "id": 15,
            "city": '浙江',
            "href": "@url(http)"
        }, {
            "id": 16,
            "city": '湖北',
            "href": "@url(http)"
        }, {
            "id": 17,
            "city": '湖南',
            "href": "@url(http)"
        }, {
            "id": 18,
            "city": '广东',
            "href": "@url(http)"
        }, {
            "id": 19,
            "city": '广西',
            "href": "@url(http)"
        }, {
            "id": 20,
            "city": '江西',
            "href": "@url(http)"
        }, {
            "id": 21,
            "city": '四川',
            "href": "@url(http)"
        }, {
            "id": 22,
            "city": '海南',
            "href": "@url(http)"
        }, {
            "id": 23,
            "city": '贵州',
            "href": "@url(http)"
        }, {
            "id": 24,
            "city": '云南',
            "href": "@url(http)"
        }, {
            "id": 25,
            "city": '西藏',
            "href": "@url(http)"
        }, {
            "id": 26,
            "city": '陕西',
            "href": "@url(http)"
        }, {
            "id": 27,
            "city": '甘肃',
            "href": "@url(http)"
        }, {
            "id": 28,
            "city": '青海',
            "href": "@url(http)"
        }, {
            "id": 29,
            "city": '宁夏',
            "href": "@url(http)"
        }, {
            "id": 30,
            "city": '新疆',
            "href": "@url(http)"
        }, {
            "id": 31,
            "city": '港澳',
            "href": "@url(http)"
        }, {
            "id": 32,
            "city": '台湾',
            "href": "@url(http)"
        }, {
            "id": 33,
            "city": '钓鱼岛',
            "href": "@url(http)"
        }, {
            "id": 34,
            "city": '海外',
            "href": "@url(http)"
        }],
        'special': [{
            "id|": 35,
            "city": '中國港澳',
            "href": "@url(http)"
        }, {
            "id|": 36,
            "city": '中國台湾',
            "href": "@url(http)"
        }, {
            "id|": 37,
            "city": '京东全球',
            "href": "@url(http)"
        }],
        "AvailableSites": [{
            "id": 38,
            "city": 'Global Site',
            "href": "@url(http)"
        }, {
            "id": 39,
            "city": 'Сайт России',
            "href": "@url(http)"
        }, {
            "id": 40,
            "city": 'Situs Indonesia',
            "href": "@url(http)"
        }, {
            "id": 41,
            "city": 'Sitio de España',
            "href": "@url(http)"
        }, {
            "id": 42,
            "city": 'เว็บไซต์ประเทศไทย',
            "href": "@url(http)"
        }]
    }


})
Mock.mock("/enterprise", {
    data: [{
        des: "企业购",
        href: "@url(http)"
    }, {
        des: "商用场景馆",
        href: "@url(http)"
    }, {
        des: "工业品",
        href: "@url(http)"
    }, {
        des: "丰客多商城",
        href: "@url(http)"
    }, {
        des: "礼品卡",
        href: "@url(http)"
    }, {
        des: "微信企业购",
        href: "@url(http)"
    }, {
        des: "大型企业采购",
        href: "@url(http)"
    }]
})
Mock.mock("/service", {
    data: {
        item1: [{
            title: "客户",
        }, {
            des: "帮助中心",
            href: '@url(http)'
        }, {
            des: "售后服务",
            href: '@url(http)'
        }, {
            des: "在线客服",
            href: '@url(http)'
        }, {
            des: "意见建议",
            href: '@url(http)'
        }, {
            des: "电话客服",
            href: '@url(http)'
        }, {
            des: "客服邮箱",
            href: '@url(http)'
        }, {
            des: "金融咨询",
            href: '@url(http)'
        }, {
            des: "全球售客服",
            href: '@url(http)'
        }, {
            des: "企业客服",
            href: '@url(http)'
        }],
        item2: [{
            title: "商户"
        }, {
            des: "合作招商",
            href: '@url(http)'
        }, {
            des: "成长中心",
            href: '@url(http)'
        }, {
            des: "商家后台",
            href: '@url(http)'
        }, {
            des: "京麦工作台",
            href: '@url(http)'
        }, {
            des: "商家帮助",
            href: '@url(http)'
        }, {
            des: "规则平台",
            href: '@url(http)'
        }]
    }
})
Mock.mock("/webSites", {
    data: {
        item1: [{
            title: "特色主题",
        }, {
            des: "首发新品",
            href: '@url(http)'
        }, {
            des: "京东金融",
            href: '@url(http)'
        }, {
            des: "全球售",
            href: '@url(http)'
        }, {
            des: "国际站",
            href: '@url(http)'
        }, {
            des: "京东会员",
            href: '@url(http)'
        }, {
            des: "台湾售",
            href: '@url(http)'
        }, {
            des: "俄语站",
            href: '@url(http)'
        }, {
            des: "装机大师",
            href: '@url(http)'
        }, {
            des: "港澳售",
            href: '@url(http)'
        }, {
            des: "优惠卷",
            href: '@url(http)'
        }, {
            des: "秒杀",
            href: '@url(http)'
        }, {
            des: "闪购",
            href: '@url(http)'
        }, {
            des: "印尼站",
            href: '@url(http)'
        }, {
            des: "陪伴计划",
            href: '@url(http)'
        }, {
            des: "出海招商",
            href: '@url(http)'
        }, {
            des: "拍拍二手",
            href: '@url(http)'
        }, {
            des: "买什么",
            href: '@url(http)'
        }, {
            des: "港澳售",
            href: '@url(http)'
        }],
        item2: [{
            title: "行业频道"
        }, {
            des: "手机",
            href: '@url(http)'
        }, {
            des: "智能数码",
            href: '@url(http)'
        }, {
            des: "玩3C",
            href: '@url(http)'
        }, {
            des: "电脑办公",
            href: '@url(http)'
        }, {
            des: "家用电器",
            href: '@url(http)'
        }, {
            des: "京鱼座智能",
            href: '@url(http)'
        }, {
            des: "京东服饰",
            href: '@url(http)'
        }, {
            des: "京东生鲜",
            href: '@url(http)'
        }, {
            des: "家装城",
            href: '@url(http)'
        }, {
            des: "母婴",
            href: '@url(http)'
        }, {
            des: "食品",
            href: '@url(http)'
        }, {
            des: "农资频道",
            href: '@url(http)'
        }, {
            des: "整车",
            href: '@url(http)'
        }, {
            des: "图书",
            href: '@url(http)'
        }, {
            des: "劳务防护",
            href: '@url(http)'
        }],
        item3: [{
            title: "生活服务"
        }, {
            des: "京东众筹",
            href: '@url(http)'
        }, {
            des: "白条",
            href: '@url(http)'
        }, {
            des: "京东金融App",
            href: '@url(http)'
        }, {
            des: "京东小金库",
            href: '@url(http)'
        }, {
            des: "理财",
            href: '@url(http)'
        }, {
            des: "话费",
            href: '@url(http)'
        }, {
            des: "水电煤",
            href: '@url(http)'
        }, {
            des: "彩票",
            href: '@url(http)'
        }, {
            des: "旅行",
            href: '@url(http)'
        }, {
            des: "机票酒店",
            href: '@url(http)'
        }, {
            des: "电影票",
            href: '@url(http)'
        }, {
            des: "京东到家",
            href: '@url(http)'
        }, {
            des: "游戏",
            href: '@url(http)'
        }, {
            des: "拍拍回收",
            href: '@url(http)'
        }],
        item4: [{
            title: "更多精选"
        }, {
            des: "合作招商",
            href: '@url(http)'
        }, {
            des: "京东通信",
            href: '@url(http)'
        }, {
            des: "京东网卡",
            href: '@url(http)'
        }, {
            des: "企业采购",
            href: '@url(http)'
        }, {
            des: "服务市场",
            href: '@url(http)'
        }, {
            des: "办公生活馆",
            href: '@url(http)'
        }, {
            des: "校园加盟",
            href: '@url(http)'
        }, {
            des: "京东社区",
            href: '@url(http)'
        }, {
            des: "游戏社区",
            href: '@url(http)'
        }, {
            des: "知识产权维权",
            href: '@url(http)'
        }]
    }
})
Mock.mock("/JD_app", {
    data: [{
        QRcode: "https://img12.360buyimg.com/img/jfs/t1/67481/15/565/28110/5cec9234E71c47244/dc4cf353fd96922e.png.webp",
        titel: "手机京东",
        href: "",
        value: "新人专享礼包",
        device: [{
            ios: "https://itunes.apple.com/cn/app/id414245413"
        }, {
            android: "https://storage.jd.com/jdmobile/JDMALL-PC2.apk"
        }, {
            ipad: "https://itunes.apple.com/cn/app/jing-dong-hd/id434374726"
        }]
    }, {
        QRcode: "https://img10.360buyimg.com/img/jfs/t1/133427/32/6189/44062/5f2a5467Efff804d1/7cbc252ed5993190.png.webp",
        titel: "关注京东JD.COM",
        href: "",
        value: "抢5元红包",
        device: []
    }, {
        QRcode: "https://img14.360buyimg.com/img/jfs/t1/36947/5/10895/15408/5cec924bE6c038530/5cf21582b416c186.jpg.webp",
        titel: "京东金融客户端",
        href: "https://m.jr.jd.com/integrate/download/html/pc.html",
        value: "新人专享礼包",
        device: [{
            ios: "https://itunes.apple.com/cn/app/jing-dong-jin-rong-hui-li/id895682747?mt=8"
        }, {
            android: "http://211.151.9.66/downapp/jrapp_jr188.apk"
        }]
    }, {
        QRcode: "https://img13.360buyimg.com/img/jfs/t1/93019/8/17752/28300/5e8c23b8E4c6c7c13/9c45c518ad785873.png.webp",
        titel: "京东健康客户端",
        href: "",
        value: "",
        device: [{
            ios: "https://hlc.m.jd.com/download/?downloadSource=jdh_JDcom"
        }, {
            android: "https://hlc.m.jd.com/download/?downloadSource=jdh_JDcom"
        }]
    }, {
        QRcode: "https://img12.360buyimg.com/img/jfs/t1/170279/40/10824/19657/6045bf7dE610d6258/3e925badd90757a3.jpg.webp",
        titel: "关注京东小程序",
        href: "",
        value: "新人0.1元购",
        device: []
    }]
})